// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/student/student.proto

package student

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetStudentListBySessionRequest struct {
	SessionId            int32    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetStudentListBySessionRequest) Reset()         { *m = GetStudentListBySessionRequest{} }
func (m *GetStudentListBySessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetStudentListBySessionRequest) ProtoMessage()    {}
func (*GetStudentListBySessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{0}
}

func (m *GetStudentListBySessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentListBySessionRequest.Unmarshal(m, b)
}
func (m *GetStudentListBySessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentListBySessionRequest.Marshal(b, m, deterministic)
}
func (m *GetStudentListBySessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentListBySessionRequest.Merge(m, src)
}
func (m *GetStudentListBySessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetStudentListBySessionRequest.Size(m)
}
func (m *GetStudentListBySessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentListBySessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentListBySessionRequest proto.InternalMessageInfo

func (m *GetStudentListBySessionRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type GetStudentListBySessionResponse struct {
	Student              []*Student `protobuf:"bytes,1,rep,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetStudentListBySessionResponse) Reset()         { *m = GetStudentListBySessionResponse{} }
func (m *GetStudentListBySessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetStudentListBySessionResponse) ProtoMessage()    {}
func (*GetStudentListBySessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{1}
}

func (m *GetStudentListBySessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStudentListBySessionResponse.Unmarshal(m, b)
}
func (m *GetStudentListBySessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStudentListBySessionResponse.Marshal(b, m, deterministic)
}
func (m *GetStudentListBySessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStudentListBySessionResponse.Merge(m, src)
}
func (m *GetStudentListBySessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetStudentListBySessionResponse.Size(m)
}
func (m *GetStudentListBySessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStudentListBySessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetStudentListBySessionResponse proto.InternalMessageInfo

func (m *GetStudentListBySessionResponse) GetStudent() []*Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type InsertAcademicSessionRequest struct {
	StudentId            string   `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	SessionId            int32    `protobuf:"varint,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAcademicSessionRequest) Reset()         { *m = InsertAcademicSessionRequest{} }
func (m *InsertAcademicSessionRequest) String() string { return proto.CompactTextString(m) }
func (*InsertAcademicSessionRequest) ProtoMessage()    {}
func (*InsertAcademicSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{2}
}

func (m *InsertAcademicSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAcademicSessionRequest.Unmarshal(m, b)
}
func (m *InsertAcademicSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAcademicSessionRequest.Marshal(b, m, deterministic)
}
func (m *InsertAcademicSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAcademicSessionRequest.Merge(m, src)
}
func (m *InsertAcademicSessionRequest) XXX_Size() int {
	return xxx_messageInfo_InsertAcademicSessionRequest.Size(m)
}
func (m *InsertAcademicSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAcademicSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAcademicSessionRequest proto.InternalMessageInfo

func (m *InsertAcademicSessionRequest) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

func (m *InsertAcademicSessionRequest) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type InsertAcademicSessionResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertAcademicSessionResponse) Reset()         { *m = InsertAcademicSessionResponse{} }
func (m *InsertAcademicSessionResponse) String() string { return proto.CompactTextString(m) }
func (*InsertAcademicSessionResponse) ProtoMessage()    {}
func (*InsertAcademicSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{3}
}

func (m *InsertAcademicSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertAcademicSessionResponse.Unmarshal(m, b)
}
func (m *InsertAcademicSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertAcademicSessionResponse.Marshal(b, m, deterministic)
}
func (m *InsertAcademicSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertAcademicSessionResponse.Merge(m, src)
}
func (m *InsertAcademicSessionResponse) XXX_Size() int {
	return xxx_messageInfo_InsertAcademicSessionResponse.Size(m)
}
func (m *InsertAcademicSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertAcademicSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertAcademicSessionResponse proto.InternalMessageInfo

type GetClassListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetClassListRequest) Reset()         { *m = GetClassListRequest{} }
func (m *GetClassListRequest) String() string { return proto.CompactTextString(m) }
func (*GetClassListRequest) ProtoMessage()    {}
func (*GetClassListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{4}
}

func (m *GetClassListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClassListRequest.Unmarshal(m, b)
}
func (m *GetClassListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClassListRequest.Marshal(b, m, deterministic)
}
func (m *GetClassListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClassListRequest.Merge(m, src)
}
func (m *GetClassListRequest) XXX_Size() int {
	return xxx_messageInfo_GetClassListRequest.Size(m)
}
func (m *GetClassListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClassListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetClassListRequest proto.InternalMessageInfo

type GetClassListResponse struct {
	Session              []*SessionClass `protobuf:"bytes,1,rep,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetClassListResponse) Reset()         { *m = GetClassListResponse{} }
func (m *GetClassListResponse) String() string { return proto.CompactTextString(m) }
func (*GetClassListResponse) ProtoMessage()    {}
func (*GetClassListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{5}
}

func (m *GetClassListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetClassListResponse.Unmarshal(m, b)
}
func (m *GetClassListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetClassListResponse.Marshal(b, m, deterministic)
}
func (m *GetClassListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetClassListResponse.Merge(m, src)
}
func (m *GetClassListResponse) XXX_Size() int {
	return xxx_messageInfo_GetClassListResponse.Size(m)
}
func (m *GetClassListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetClassListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetClassListResponse proto.InternalMessageInfo

func (m *GetClassListResponse) GetSession() []*SessionClass {
	if m != nil {
		return m.Session
	}
	return nil
}

type SessionClass struct {
	SessionId            int32    `protobuf:"varint,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Class                string   `protobuf:"bytes,2,opt,name=class,proto3" json:"class,omitempty"`
	Year                 string   `protobuf:"bytes,3,opt,name=year,proto3" json:"year,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionClass) Reset()         { *m = SessionClass{} }
func (m *SessionClass) String() string { return proto.CompactTextString(m) }
func (*SessionClass) ProtoMessage()    {}
func (*SessionClass) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{6}
}

func (m *SessionClass) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionClass.Unmarshal(m, b)
}
func (m *SessionClass) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionClass.Marshal(b, m, deterministic)
}
func (m *SessionClass) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionClass.Merge(m, src)
}
func (m *SessionClass) XXX_Size() int {
	return xxx_messageInfo_SessionClass.Size(m)
}
func (m *SessionClass) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionClass.DiscardUnknown(m)
}

var xxx_messageInfo_SessionClass proto.InternalMessageInfo

func (m *SessionClass) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *SessionClass) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *SessionClass) GetYear() string {
	if m != nil {
		return m.Year
	}
	return ""
}

type StudentListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentListRequest) Reset()         { *m = StudentListRequest{} }
func (m *StudentListRequest) String() string { return proto.CompactTextString(m) }
func (*StudentListRequest) ProtoMessage()    {}
func (*StudentListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{7}
}

func (m *StudentListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentListRequest.Unmarshal(m, b)
}
func (m *StudentListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentListRequest.Marshal(b, m, deterministic)
}
func (m *StudentListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentListRequest.Merge(m, src)
}
func (m *StudentListRequest) XXX_Size() int {
	return xxx_messageInfo_StudentListRequest.Size(m)
}
func (m *StudentListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentListRequest proto.InternalMessageInfo

type StudentListResponse struct {
	Student              []*Student `protobuf:"bytes,1,rep,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *StudentListResponse) Reset()         { *m = StudentListResponse{} }
func (m *StudentListResponse) String() string { return proto.CompactTextString(m) }
func (*StudentListResponse) ProtoMessage()    {}
func (*StudentListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{8}
}

func (m *StudentListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentListResponse.Unmarshal(m, b)
}
func (m *StudentListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentListResponse.Marshal(b, m, deterministic)
}
func (m *StudentListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentListResponse.Merge(m, src)
}
func (m *StudentListResponse) XXX_Size() int {
	return xxx_messageInfo_StudentListResponse.Size(m)
}
func (m *StudentListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StudentListResponse proto.InternalMessageInfo

func (m *StudentListResponse) GetStudent() []*Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type InsertRequest struct {
	Student              *Student `protobuf:"bytes,1,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{9}
}

func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (m *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(m, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type CheckStudentRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStudentRequest) Reset()         { *m = CheckStudentRequest{} }
func (m *CheckStudentRequest) String() string { return proto.CompactTextString(m) }
func (*CheckStudentRequest) ProtoMessage()    {}
func (*CheckStudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{10}
}

func (m *CheckStudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStudentRequest.Unmarshal(m, b)
}
func (m *CheckStudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStudentRequest.Marshal(b, m, deterministic)
}
func (m *CheckStudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStudentRequest.Merge(m, src)
}
func (m *CheckStudentRequest) XXX_Size() int {
	return xxx_messageInfo_CheckStudentRequest.Size(m)
}
func (m *CheckStudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStudentRequest proto.InternalMessageInfo

func (m *CheckStudentRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CheckStudentResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Student              *Student `protobuf:"bytes,4,opt,name=student,proto3" json:"student,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStudentResponse) Reset()         { *m = CheckStudentResponse{} }
func (m *CheckStudentResponse) String() string { return proto.CompactTextString(m) }
func (*CheckStudentResponse) ProtoMessage()    {}
func (*CheckStudentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{11}
}

func (m *CheckStudentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStudentResponse.Unmarshal(m, b)
}
func (m *CheckStudentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStudentResponse.Marshal(b, m, deterministic)
}
func (m *CheckStudentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStudentResponse.Merge(m, src)
}
func (m *CheckStudentResponse) XXX_Size() int {
	return xxx_messageInfo_CheckStudentResponse.Size(m)
}
func (m *CheckStudentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStudentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStudentResponse proto.InternalMessageInfo

func (m *CheckStudentResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *CheckStudentResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *CheckStudentResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CheckStudentResponse) GetStudent() *Student {
	if m != nil {
		return m.Student
	}
	return nil
}

type Student struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StdId                string               `protobuf:"bytes,2,opt,name=std_id,json=stdId,proto3" json:"std_id,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	NameBn               string               `protobuf:"bytes,4,opt,name=name_bn,json=nameBn,proto3" json:"name_bn,omitempty"`
	FathersName          string               `protobuf:"bytes,5,opt,name=fathers_name,json=fathersName,proto3" json:"fathers_name,omitempty"`
	MothersName          string               `protobuf:"bytes,6,opt,name=mothers_name,json=mothersName,proto3" json:"mothers_name,omitempty"`
	Dob                  *timestamp.Timestamp `protobuf:"bytes,7,opt,name=dob,proto3" json:"dob,omitempty"`
	Gender               string               `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	BloodGroup           string               `protobuf:"bytes,9,opt,name=blood_group,json=bloodGroup,proto3" json:"blood_group,omitempty"`
	MobileNumber         string               `protobuf:"bytes,10,opt,name=mobile_number,json=mobileNumber,proto3" json:"mobile_number,omitempty"`
	Session              string               `protobuf:"bytes,11,opt,name=session,proto3" json:"session,omitempty"`
	ClassName            string               `protobuf:"bytes,12,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ClassSection         string               `protobuf:"bytes,13,opt,name=class_section,json=classSection,proto3" json:"class_section,omitempty"`
	ClassGroup           string               `protobuf:"bytes,14,opt,name=class_group,json=classGroup,proto3" json:"class_group,omitempty"`
	ClassRoll            string               `protobuf:"bytes,15,opt,name=class_roll,json=classRoll,proto3" json:"class_roll,omitempty"`
	Address              string               `protobuf:"bytes,16,opt,name=address,proto3" json:"address,omitempty"`
	Religion             string               `protobuf:"bytes,17,opt,name=religion,proto3" json:"religion,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy            string               `protobuf:"bytes,20,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy            string               `protobuf:"bytes,21,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Email                string               `protobuf:"bytes,22,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{12}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Student) GetStdId() string {
	if m != nil {
		return m.StdId
	}
	return ""
}

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetNameBn() string {
	if m != nil {
		return m.NameBn
	}
	return ""
}

func (m *Student) GetFathersName() string {
	if m != nil {
		return m.FathersName
	}
	return ""
}

func (m *Student) GetMothersName() string {
	if m != nil {
		return m.MothersName
	}
	return ""
}

func (m *Student) GetDob() *timestamp.Timestamp {
	if m != nil {
		return m.Dob
	}
	return nil
}

func (m *Student) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Student) GetBloodGroup() string {
	if m != nil {
		return m.BloodGroup
	}
	return ""
}

func (m *Student) GetMobileNumber() string {
	if m != nil {
		return m.MobileNumber
	}
	return ""
}

func (m *Student) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *Student) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *Student) GetClassSection() string {
	if m != nil {
		return m.ClassSection
	}
	return ""
}

func (m *Student) GetClassGroup() string {
	if m != nil {
		return m.ClassGroup
	}
	return ""
}

func (m *Student) GetClassRoll() string {
	if m != nil {
		return m.ClassRoll
	}
	return ""
}

func (m *Student) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Student) GetReligion() string {
	if m != nil {
		return m.Religion
	}
	return ""
}

func (m *Student) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Student) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Student) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Student) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *Student) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type InsertResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	StdId                string   `protobuf:"bytes,3,opt,name=stdId,proto3" json:"stdId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertResponse) Reset()         { *m = InsertResponse{} }
func (m *InsertResponse) String() string { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()    {}
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{13}
}

func (m *InsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertResponse.Unmarshal(m, b)
}
func (m *InsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertResponse.Marshal(b, m, deterministic)
}
func (m *InsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertResponse.Merge(m, src)
}
func (m *InsertResponse) XXX_Size() int {
	return xxx_messageInfo_InsertResponse.Size(m)
}
func (m *InsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertResponse proto.InternalMessageInfo

func (m *InsertResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *InsertResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *InsertResponse) GetStdId() string {
	if m != nil {
		return m.StdId
	}
	return ""
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Phone                string   `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{14}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type LoginResponse struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_620022a97f369315, []int{15}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *LoginResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*GetStudentListBySessionRequest)(nil), "student.GetStudentListBySessionRequest")
	proto.RegisterType((*GetStudentListBySessionResponse)(nil), "student.GetStudentListBySessionResponse")
	proto.RegisterType((*InsertAcademicSessionRequest)(nil), "student.InsertAcademicSessionRequest")
	proto.RegisterType((*InsertAcademicSessionResponse)(nil), "student.InsertAcademicSessionResponse")
	proto.RegisterType((*GetClassListRequest)(nil), "student.GetClassListRequest")
	proto.RegisterType((*GetClassListResponse)(nil), "student.GetClassListResponse")
	proto.RegisterType((*SessionClass)(nil), "student.SessionClass")
	proto.RegisterType((*StudentListRequest)(nil), "student.StudentListRequest")
	proto.RegisterType((*StudentListResponse)(nil), "student.StudentListResponse")
	proto.RegisterType((*InsertRequest)(nil), "student.InsertRequest")
	proto.RegisterType((*CheckStudentRequest)(nil), "student.CheckStudentRequest")
	proto.RegisterType((*CheckStudentResponse)(nil), "student.CheckStudentResponse")
	proto.RegisterType((*Student)(nil), "student.Student")
	proto.RegisterType((*InsertResponse)(nil), "student.InsertResponse")
	proto.RegisterType((*LoginRequest)(nil), "student.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "student.LoginResponse")
}

func init() {
	proto.RegisterFile("pb/student/student.proto", fileDescriptor_620022a97f369315)
}

var fileDescriptor_620022a97f369315 = []byte{
	// 885 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x8e, 0xe2, 0x46,
	0x10, 0x5d, 0x86, 0x01, 0x96, 0xe2, 0x92, 0x4d, 0x73, 0x19, 0xcb, 0x61, 0xc2, 0xae, 0x57, 0x49,
	0x46, 0x51, 0x02, 0xd2, 0xe6, 0x25, 0xd1, 0x4a, 0x91, 0x60, 0x23, 0x21, 0xa2, 0xdd, 0x79, 0x30,
	0xa3, 0x3c, 0xcc, 0x0b, 0xb2, 0x71, 0x0f, 0x58, 0x63, 0xbb, 0x9d, 0xee, 0x76, 0x22, 0x7e, 0x21,
	0xbf, 0x16, 0xe5, 0x9f, 0xa2, 0xbe, 0x19, 0xc3, 0xc2, 0x20, 0xcd, 0x13, 0xd4, 0xa9, 0x53, 0x5d,
	0xa7, 0xca, 0xae, 0x6a, 0x83, 0x95, 0xfa, 0x63, 0xc6, 0xb3, 0x00, 0x27, 0xdc, 0xfc, 0x8e, 0x52,
	0x4a, 0x38, 0x41, 0x35, 0x6d, 0xda, 0xc3, 0x35, 0x21, 0xeb, 0x08, 0x8f, 0x25, 0xec, 0x67, 0x0f,
	0x63, 0x1e, 0xc6, 0x98, 0x71, 0x2f, 0x4e, 0x15, 0xd3, 0xf9, 0x15, 0xbe, 0x9e, 0x61, 0xbe, 0x50,
	0xf4, 0x8f, 0x21, 0xe3, 0xd3, 0xed, 0x02, 0x33, 0x16, 0x92, 0xc4, 0xc5, 0x7f, 0x66, 0x98, 0x71,
	0x34, 0x80, 0x3a, 0x53, 0xc8, 0x3c, 0xb0, 0x4a, 0xaf, 0x4b, 0x37, 0x15, 0x77, 0x07, 0x38, 0x9f,
	0x60, 0x78, 0x32, 0x9e, 0xa5, 0x24, 0x61, 0x18, 0x7d, 0x0f, 0x46, 0x8e, 0x55, 0x7a, 0x5d, 0xbe,
	0x69, 0xbc, 0x7b, 0x35, 0x32, 0x6a, 0x75, 0x9c, 0x6b, 0x08, 0xce, 0x3d, 0x0c, 0xe6, 0x09, 0xc3,
	0x94, 0x4f, 0x56, 0x5e, 0x80, 0xe3, 0x70, 0x75, 0x44, 0x8c, 0xa2, 0x6a, 0x31, 0x75, 0x77, 0x07,
	0xec, 0x4b, 0xbd, 0x38, 0x94, 0x3a, 0x84, 0xeb, 0x13, 0x67, 0x2b, 0xa1, 0x4e, 0x0f, 0x3a, 0x33,
	0xcc, 0x3f, 0x44, 0x1e, 0x63, 0xa2, 0x12, 0x9d, 0xd3, 0x99, 0x41, 0x77, 0x1f, 0xd6, 0x75, 0x8d,
	0xa1, 0xa6, 0x0f, 0xd7, 0x75, 0xf5, 0x76, 0x75, 0x29, 0x5c, 0xc6, 0xb8, 0x86, 0xe5, 0xfc, 0x01,
	0xcd, 0xa2, 0xe3, 0xe9, 0xce, 0xa2, 0x2e, 0x54, 0x56, 0x82, 0x26, 0x0b, 0xa9, 0xbb, 0xca, 0x40,
	0x08, 0x2e, 0xb7, 0xd8, 0xa3, 0x56, 0x59, 0x82, 0xf2, 0xbf, 0xd3, 0x05, 0x54, 0x78, 0x00, 0x46,
	0xf6, 0x04, 0x3a, 0x7b, 0xe8, 0x33, 0x9e, 0xc6, 0x7b, 0x68, 0xa9, 0x8e, 0x99, 0xf6, 0xef, 0x05,
	0x97, 0x9e, 0x0e, 0xfe, 0x11, 0x3a, 0x1f, 0x36, 0x78, 0xf5, 0x68, 0x1c, 0xfa, 0x88, 0x3e, 0x54,
	0x33, 0x86, 0xe9, 0xfc, 0x37, 0xfd, 0xf8, 0xb4, 0xe5, 0xfc, 0x53, 0x82, 0xee, 0x3e, 0x5f, 0x0b,
	0xee, 0x43, 0x95, 0x71, 0x8f, 0x67, 0x4c, 0x06, 0x94, 0x5d, 0x6d, 0x89, 0xfe, 0x60, 0x4a, 0x09,
	0x35, 0xfd, 0x91, 0x06, 0xb2, 0xa0, 0x16, 0x63, 0xc6, 0xbc, 0x35, 0xd6, 0x2d, 0x32, 0x66, 0x51,
	0xfb, 0xe5, 0x39, 0xed, 0xff, 0x55, 0xa0, 0xa6, 0x41, 0xd4, 0x86, 0x8b, 0xd0, 0xbc, 0x6b, 0x17,
	0x61, 0x80, 0x7a, 0x42, 0x4f, 0xb0, 0x0c, 0x03, 0x93, 0x98, 0xf1, 0x60, 0x1e, 0x88, 0x07, 0x93,
	0x78, 0xb1, 0xc9, 0x2a, 0xff, 0xa3, 0x2b, 0xa8, 0x89, 0xdf, 0xa5, 0x9f, 0xc8, 0x94, 0x75, 0xb7,
	0x2a, 0xcc, 0x69, 0x82, 0xde, 0x40, 0xf3, 0xc1, 0xe3, 0x1b, 0x4c, 0xd9, 0x52, 0x06, 0x55, 0xa4,
	0xb7, 0xa1, 0xb1, 0x5b, 0x11, 0xfb, 0x06, 0x9a, 0x31, 0x29, 0x50, 0xaa, 0x8a, 0xa2, 0x31, 0x49,
	0xf9, 0x01, 0xca, 0x01, 0xf1, 0xad, 0x9a, 0xac, 0xc6, 0x1e, 0xa9, 0x51, 0x1f, 0x99, 0x51, 0x1f,
	0xdd, 0x99, 0x51, 0x77, 0x05, 0x4d, 0xf4, 0x71, 0x8d, 0x93, 0x00, 0x53, 0xeb, 0xa5, 0xd2, 0xa2,
	0x2c, 0x34, 0x84, 0x86, 0x1f, 0x11, 0x12, 0x2c, 0xd7, 0x94, 0x64, 0xa9, 0x55, 0x97, 0x4e, 0x90,
	0xd0, 0x4c, 0x20, 0xe8, 0x2d, 0xb4, 0x62, 0xe2, 0x87, 0x11, 0x5e, 0x26, 0x59, 0xec, 0x63, 0x6a,
	0x81, 0xa4, 0x34, 0x15, 0x78, 0x2b, 0x31, 0xd1, 0x77, 0x33, 0x0c, 0x0d, 0xd5, 0x77, 0x6d, 0xa2,
	0x6b, 0x00, 0xf9, 0xea, 0xaa, 0x32, 0x9a, 0x6a, 0x66, 0x25, 0x22, 0x8b, 0x78, 0x0b, 0x2d, 0xe5,
	0x66, 0x78, 0xc5, 0x45, 0x78, 0x4b, 0x9d, 0x2e, 0xc1, 0x85, 0xc2, 0x84, 0x46, 0x45, 0x52, 0x1a,
	0xdb, 0x4a, 0xa3, 0x84, 0x94, 0xc6, 0x3c, 0x09, 0x25, 0x51, 0x64, 0x7d, 0x51, 0x48, 0xe2, 0x92,
	0x28, 0x12, 0xea, 0xbc, 0x20, 0xa0, 0x98, 0x31, 0xeb, 0x95, 0x52, 0xa7, 0x4d, 0x64, 0xc3, 0x4b,
	0x8a, 0xa3, 0x70, 0x2d, 0x32, 0x7f, 0x29, 0x5d, 0xb9, 0x8d, 0x7e, 0x01, 0x58, 0x51, 0xec, 0x71,
	0x1c, 0x2c, 0x3d, 0x6e, 0xa1, 0xb3, 0x6d, 0xae, 0x6b, 0xf6, 0x84, 0x8b, 0xd0, 0x2c, 0x0d, 0x4c,
	0x68, 0xe7, 0x7c, 0xa8, 0x66, 0x4f, 0xb8, 0x2c, 0x45, 0x67, 0xf5, 0xb7, 0x56, 0x57, 0x97, 0xa2,
	0x90, 0xe9, 0x56, 0xb8, 0xcd, 0xc9, 0xfe, 0xd6, 0xea, 0x29, 0xb7, 0x46, 0xa6, 0x5b, 0x39, 0x15,
	0xb1, 0x17, 0x46, 0x56, 0x5f, 0x4f, 0x85, 0x30, 0x9c, 0x3b, 0x68, 0x9b, 0x41, 0x7e, 0xd6, 0x54,
	0x75, 0x41, 0xbd, 0xe5, 0xfa, 0xed, 0x56, 0x86, 0xd8, 0x67, 0x1f, 0xc9, 0x3a, 0xcc, 0x97, 0x73,
	0x9e, 0xbb, 0x54, 0xc8, 0x2d, 0x3a, 0x9c, 0x7a, 0x8c, 0xfd, 0x4d, 0xa8, 0x99, 0x98, 0xdc, 0x16,
	0x11, 0xe9, 0x86, 0x24, 0x66, 0x6a, 0x94, 0xe1, 0x2c, 0xa0, 0xa5, 0xcf, 0x7d, 0xae, 0x58, 0x4e,
	0x1e, 0x71, 0x62, 0x0e, 0x95, 0xc6, 0xbb, 0x7f, 0x2f, 0xa1, 0xad, 0x47, 0x7a, 0x81, 0xe9, 0x5f,
	0xe1, 0x0a, 0xa3, 0xf7, 0x50, 0x55, 0x5d, 0x41, 0xfd, 0x7c, 0x15, 0xec, 0xed, 0x3b, 0xfb, 0xea,
	0x33, 0x5c, 0x5f, 0x15, 0x2f, 0xd0, 0xcf, 0x50, 0x91, 0x22, 0xd1, 0x6e, 0xeb, 0x17, 0x9b, 0x61,
	0xf7, 0x0f, 0xe1, 0x3c, 0xf2, 0x13, 0x34, 0x8b, 0x8b, 0x0e, 0x0d, 0x72, 0xe6, 0x91, 0x7d, 0x69,
	0x5f, 0x9f, 0xf0, 0xe6, 0xc7, 0xfd, 0x0e, 0x8d, 0xc2, 0x9e, 0x47, 0x5f, 0x1d, 0x6e, 0xb5, 0xc2,
	0x9d, 0x60, 0x0f, 0x8e, 0x3b, 0x8b, 0xd2, 0x8a, 0x57, 0x5d, 0x41, 0xda, 0x91, 0x8b, 0xb1, 0x20,
	0xed, 0xd8, 0xfd, 0xe8, 0xbc, 0x40, 0x1b, 0xe8, 0x1d, 0xbd, 0x71, 0xd1, 0x37, 0x07, 0x7d, 0x3d,
	0x7e, 0xdb, 0xdb, 0xdf, 0x9e, 0xa3, 0xe5, 0x99, 0x12, 0xb8, 0x3a, 0xf1, 0x19, 0x82, 0xbe, 0x2b,
	0xaa, 0x7c, 0xe2, 0x43, 0xc7, 0xbe, 0x39, 0x4f, 0x34, 0xf9, 0xa6, 0xed, 0xfb, 0xe6, 0x68, 0xbc,
	0xfb, 0xfc, 0xf2, 0xab, 0x72, 0xa6, 0x7f, 0xfa, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x10, 0x9b, 0x4f,
	0x37, 0x93, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StudentServiceClient is the client API for StudentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StudentServiceClient interface {
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// rpc Validate(ValidateRequest) returns (ValidateResponse) {}
	CheckStudent(ctx context.Context, in *CheckStudentRequest, opts ...grpc.CallOption) (*CheckStudentResponse, error)
	StudentList(ctx context.Context, in *StudentListRequest, opts ...grpc.CallOption) (*StudentListResponse, error)
	GetClassList(ctx context.Context, in *GetClassListRequest, opts ...grpc.CallOption) (*GetClassListResponse, error)
	InsertAcademicSession(ctx context.Context, in *InsertAcademicSessionRequest, opts ...grpc.CallOption) (*InsertAcademicSessionResponse, error)
	GetStudentListBySession(ctx context.Context, in *GetStudentListBySessionRequest, opts ...grpc.CallOption) (*GetStudentListBySessionResponse, error)
}

type studentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStudentServiceClient(cc grpc.ClientConnInterface) StudentServiceClient {
	return &studentServiceClient{cc}
}

func (c *studentServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) CheckStudent(ctx context.Context, in *CheckStudentRequest, opts ...grpc.CallOption) (*CheckStudentResponse, error) {
	out := new(CheckStudentResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/CheckStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) StudentList(ctx context.Context, in *StudentListRequest, opts ...grpc.CallOption) (*StudentListResponse, error) {
	out := new(StudentListResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/StudentList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetClassList(ctx context.Context, in *GetClassListRequest, opts ...grpc.CallOption) (*GetClassListResponse, error) {
	out := new(GetClassListResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/GetClassList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) InsertAcademicSession(ctx context.Context, in *InsertAcademicSessionRequest, opts ...grpc.CallOption) (*InsertAcademicSessionResponse, error) {
	out := new(InsertAcademicSessionResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/InsertAcademicSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *studentServiceClient) GetStudentListBySession(ctx context.Context, in *GetStudentListBySessionRequest, opts ...grpc.CallOption) (*GetStudentListBySessionResponse, error) {
	out := new(GetStudentListBySessionResponse)
	err := c.cc.Invoke(ctx, "/student.StudentService/GetStudentListBySession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StudentServiceServer is the server API for StudentService service.
type StudentServiceServer interface {
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// rpc Validate(ValidateRequest) returns (ValidateResponse) {}
	CheckStudent(context.Context, *CheckStudentRequest) (*CheckStudentResponse, error)
	StudentList(context.Context, *StudentListRequest) (*StudentListResponse, error)
	GetClassList(context.Context, *GetClassListRequest) (*GetClassListResponse, error)
	InsertAcademicSession(context.Context, *InsertAcademicSessionRequest) (*InsertAcademicSessionResponse, error)
	GetStudentListBySession(context.Context, *GetStudentListBySessionRequest) (*GetStudentListBySessionResponse, error)
}

// UnimplementedStudentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStudentServiceServer struct {
}

func (*UnimplementedStudentServiceServer) Insert(ctx context.Context, req *InsertRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (*UnimplementedStudentServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedStudentServiceServer) CheckStudent(ctx context.Context, req *CheckStudentRequest) (*CheckStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStudent not implemented")
}
func (*UnimplementedStudentServiceServer) StudentList(ctx context.Context, req *StudentListRequest) (*StudentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StudentList not implemented")
}
func (*UnimplementedStudentServiceServer) GetClassList(ctx context.Context, req *GetClassListRequest) (*GetClassListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassList not implemented")
}
func (*UnimplementedStudentServiceServer) InsertAcademicSession(ctx context.Context, req *InsertAcademicSessionRequest) (*InsertAcademicSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertAcademicSession not implemented")
}
func (*UnimplementedStudentServiceServer) GetStudentListBySession(ctx context.Context, req *GetStudentListBySessionRequest) (*GetStudentListBySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentListBySession not implemented")
}

func RegisterStudentServiceServer(s *grpc.Server, srv StudentServiceServer) {
	s.RegisterService(&_StudentService_serviceDesc, srv)
}

func _StudentService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_CheckStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).CheckStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/CheckStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).CheckStudent(ctx, req.(*CheckStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_StudentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).StudentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/StudentList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).StudentList(ctx, req.(*StudentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetClassList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetClassList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/GetClassList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetClassList(ctx, req.(*GetClassListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_InsertAcademicSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertAcademicSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).InsertAcademicSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/InsertAcademicSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).InsertAcademicSession(ctx, req.(*InsertAcademicSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StudentService_GetStudentListBySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentListBySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StudentServiceServer).GetStudentListBySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.StudentService/GetStudentListBySession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StudentServiceServer).GetStudentListBySession(ctx, req.(*GetStudentListBySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StudentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "student.StudentService",
	HandlerType: (*StudentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _StudentService_Insert_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _StudentService_Login_Handler,
		},
		{
			MethodName: "CheckStudent",
			Handler:    _StudentService_CheckStudent_Handler,
		},
		{
			MethodName: "StudentList",
			Handler:    _StudentService_StudentList_Handler,
		},
		{
			MethodName: "GetClassList",
			Handler:    _StudentService_GetClassList_Handler,
		},
		{
			MethodName: "InsertAcademicSession",
			Handler:    _StudentService_InsertAcademicSession_Handler,
		},
		{
			MethodName: "GetStudentListBySession",
			Handler:    _StudentService_GetStudentListBySession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/student/student.proto",
}
