// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/student

package student

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("pb/student", fileDescriptor_5c750a8dac2abe2f)
}

var fileDescriptor_5c750a8dac2abe2f = []byte{
	// 36 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x48, 0xd2, 0x2f,
	0x2e, 0x29, 0x4d, 0x49, 0xcd, 0x2b, 0x01, 0x04, 0x00, 0x00, 0xff, 0xff, 0x87, 0x5a, 0x88, 0xfd,
	0x0c, 0x00, 0x00, 0x00,
}
